server:
  port: 8080

spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.117.100:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: 1111
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.117.101:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: 1111
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #负载均衡  使从库轮询查询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    #允许bean定义覆盖
    allow-bean-definition-overriding: true
  #用本机的redis先测试，后期上线在用linux的
  redis:
    host: localhost
    port: 6379
    database: 0
    #password: 1111
  cache:
    redis:
      time-to-live: 1800000 #设置缓存有效期(30min)

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #address_book ---> AddressBook 类似这样的映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: E:\IDEA项目文件\reggie项目资料\1 瑞吉外卖项目\资料\图片资源\